services:
  go-practice: # サービス名
    container_name: go-practice
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./build/Dockerfile
    volumes: # マウントディレクトリ
      - .:/go-practice
    tty: true # コンテナの永続化
    env_file: # .envファイル
      - ./build/.go_env
    environment:
      - TZ=Asia/Tokyo
      - DBUSER=root
      - DBPASS=example

  db:
    image: mysql
    environment:  
      MYSQL_USER: go_practice
      MYSQL_PASSWORD: go_practice
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/:/etc/mysql/conf.d

volumes:
  db_data:
